name: "🌇 GitHub Skyline 3D calendar"
category: github
description: |
  This plugins lets you display your 3D commits calendar from [skyline.github.com](https://skyline.github.com/).
  > ⚠️ This plugin significantly increase file size, consider using it as standalone.
examples:
  default: https://github.com/lowlighter/metrics/blob/examples/metrics.plugin.skyline.svg
index: 25
supports:
  - user
scopes: []
inputs:

  plugin_skyline:
    description: Enable skyline plugin
    type: boolean
    default: no

  plugin_skyline_year:
    description: Displayed year
    type: number
    default: 2021
    min: 2008

  plugin_skyline_frames:
    description: |
      Frames count
      Use 120 for a full-loop and 60 for a half-loop.
      A higher number of frames will increase file size.
    type: number
    default: 120
    min: 1
    max: 120

  plugin_skyline_quality:
    description: |
      Image quality
      A higher image quality will increase file size.
    type: number
    default: 1
    min: 0.1
    max: 1

  plugin_skyline_compatibility:
    description: |
      Compatibility mode
      This uses CSS animations rather than embedded GIF to support a widerr range of browser, like Firefox and Safari.
      Using this mode significantly increase file size as each frame is encoded separately
    type: boolean
    default: no