name: GitHub Skyline
on:
  schedule:
    - cron: "21 6,18 * * *"
  workflow_dispatch:
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Skyline
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.skyline.svg
          token: NOT_NEEDED
          base: ''
          plugin_skyline: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
